// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: snowflake_id_server.proto

package server

import (
	"context"

	"snowflake_id_server/internal/logic"
	"snowflake_id_server/internal/svc"
	"snowflake_id_server/snowflake_id_server"
)

type SnowflakeIdServerServer struct {
	svcCtx *svc.ServiceContext
	snowflake_id_server.UnimplementedSnowflakeIdServerServer
}

func NewSnowflakeIdServerServer(svcCtx *svc.ServiceContext) *SnowflakeIdServerServer {
	return &SnowflakeIdServerServer{
		svcCtx: svcCtx,
	}
}

func (s *SnowflakeIdServerServer) Ping(ctx context.Context, in *snowflake_id_server.Request) (*snowflake_id_server.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *SnowflakeIdServerServer) GetID(ctx context.Context, in *snowflake_id_server.Request) (*snowflake_id_server.GetIDResp, error) {
	l := logic.NewGetIDLogic(ctx, s.svcCtx)
	return l.GetID(in)
}
