// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.19.4
// source: snowflake_id_server.proto

package snowflake_id_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqID string `protobuf:"bytes,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_snowflake_id_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_snowflake_id_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_snowflake_id_server_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetReqID() string {
	if x != nil {
		return x.ReqID
	}
	return ""
}

type PingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespID  string `protobuf:"bytes,1,opt,name=respID,proto3" json:"respID,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Time    string `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_snowflake_id_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_snowflake_id_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_snowflake_id_server_proto_rawDescGZIP(), []int{1}
}

func (x *PingResp) GetRespID() string {
	if x != nil {
		return x.RespID
	}
	return ""
}

func (x *PingResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResp) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type GetIDResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespID string `protobuf:"bytes,1,opt,name=respID,proto3" json:"respID,omitempty"`
	ID     int64  `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetIDResp) Reset() {
	*x = GetIDResp{}
	mi := &file_snowflake_id_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIDResp) ProtoMessage() {}

func (x *GetIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_snowflake_id_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIDResp.ProtoReflect.Descriptor instead.
func (*GetIDResp) Descriptor() ([]byte, []int) {
	return file_snowflake_id_server_proto_rawDescGZIP(), []int{2}
}

func (x *GetIDResp) GetRespID() string {
	if x != nil {
		return x.RespID
	}
	return ""
}

func (x *GetIDResp) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_snowflake_id_server_proto protoreflect.FileDescriptor

var file_snowflake_id_server_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x73, 0x6e, 0x6f,
	0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x22, 0x1f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x65, 0x71, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49,
	0x44, 0x22, 0x50, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x70, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x70, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x32, 0xa1, 0x01, 0x0a, 0x13, 0x53, 0x6e, 0x6f,
	0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x12, 0x43, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x2e, 0x73, 0x6e, 0x6f, 0x77, 0x66,
	0x6c, 0x61, 0x6b, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61,
	0x6b, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x45, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x49, 0x44, 0x12, 0x1c,
	0x2e, 0x73, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73,
	0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x42, 0x17, 0x5a, 0x15,
	0x2e, 0x2f, 0x73, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_snowflake_id_server_proto_rawDescOnce sync.Once
	file_snowflake_id_server_proto_rawDescData = file_snowflake_id_server_proto_rawDesc
)

func file_snowflake_id_server_proto_rawDescGZIP() []byte {
	file_snowflake_id_server_proto_rawDescOnce.Do(func() {
		file_snowflake_id_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_snowflake_id_server_proto_rawDescData)
	})
	return file_snowflake_id_server_proto_rawDescData
}

var file_snowflake_id_server_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_snowflake_id_server_proto_goTypes = []any{
	(*Request)(nil),   // 0: snowflake_id_server.Request
	(*PingResp)(nil),  // 1: snowflake_id_server.PingResp
	(*GetIDResp)(nil), // 2: snowflake_id_server.GetIDResp
}
var file_snowflake_id_server_proto_depIdxs = []int32{
	0, // 0: snowflake_id_server.Snowflake_id_server.Ping:input_type -> snowflake_id_server.Request
	0, // 1: snowflake_id_server.Snowflake_id_server.GetID:input_type -> snowflake_id_server.Request
	1, // 2: snowflake_id_server.Snowflake_id_server.Ping:output_type -> snowflake_id_server.PingResp
	2, // 3: snowflake_id_server.Snowflake_id_server.GetID:output_type -> snowflake_id_server.GetIDResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_snowflake_id_server_proto_init() }
func file_snowflake_id_server_proto_init() {
	if File_snowflake_id_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snowflake_id_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snowflake_id_server_proto_goTypes,
		DependencyIndexes: file_snowflake_id_server_proto_depIdxs,
		MessageInfos:      file_snowflake_id_server_proto_msgTypes,
	}.Build()
	File_snowflake_id_server_proto = out.File
	file_snowflake_id_server_proto_rawDesc = nil
	file_snowflake_id_server_proto_goTypes = nil
	file_snowflake_id_server_proto_depIdxs = nil
}
