// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: snowflake_id_server.proto

package snowflake_id_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnowflakeIdServer_Ping_FullMethodName  = "/snowflake_id_server.Snowflake_id_server/Ping"
	SnowflakeIdServer_GetID_FullMethodName = "/snowflake_id_server.Snowflake_id_server/GetID"
)

// SnowflakeIdServerClient is the client API for SnowflakeIdServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnowflakeIdServerClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*PingResp, error)
	GetID(ctx context.Context, in *Request, opts ...grpc.CallOption) (*GetIDResp, error)
}

type snowflakeIdServerClient struct {
	cc grpc.ClientConnInterface
}

func NewSnowflakeIdServerClient(cc grpc.ClientConnInterface) SnowflakeIdServerClient {
	return &snowflakeIdServerClient{cc}
}

func (c *snowflakeIdServerClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*PingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResp)
	err := c.cc.Invoke(ctx, SnowflakeIdServer_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snowflakeIdServerClient) GetID(ctx context.Context, in *Request, opts ...grpc.CallOption) (*GetIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIDResp)
	err := c.cc.Invoke(ctx, SnowflakeIdServer_GetID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnowflakeIdServerServer is the server API for SnowflakeIdServer service.
// All implementations must embed UnimplementedSnowflakeIdServerServer
// for forward compatibility.
type SnowflakeIdServerServer interface {
	Ping(context.Context, *Request) (*PingResp, error)
	GetID(context.Context, *Request) (*GetIDResp, error)
	mustEmbedUnimplementedSnowflakeIdServerServer()
}

// UnimplementedSnowflakeIdServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnowflakeIdServerServer struct{}

func (UnimplementedSnowflakeIdServerServer) Ping(context.Context, *Request) (*PingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSnowflakeIdServerServer) GetID(context.Context, *Request) (*GetIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetID not implemented")
}
func (UnimplementedSnowflakeIdServerServer) mustEmbedUnimplementedSnowflakeIdServerServer() {}
func (UnimplementedSnowflakeIdServerServer) testEmbeddedByValue()                           {}

// UnsafeSnowflakeIdServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnowflakeIdServerServer will
// result in compilation errors.
type UnsafeSnowflakeIdServerServer interface {
	mustEmbedUnimplementedSnowflakeIdServerServer()
}

func RegisterSnowflakeIdServerServer(s grpc.ServiceRegistrar, srv SnowflakeIdServerServer) {
	// If the following call pancis, it indicates UnimplementedSnowflakeIdServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnowflakeIdServer_ServiceDesc, srv)
}

func _SnowflakeIdServer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowflakeIdServerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnowflakeIdServer_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowflakeIdServerServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnowflakeIdServer_GetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowflakeIdServerServer).GetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnowflakeIdServer_GetID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowflakeIdServerServer).GetID(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SnowflakeIdServer_ServiceDesc is the grpc.ServiceDesc for SnowflakeIdServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnowflakeIdServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snowflake_id_server.Snowflake_id_server",
	HandlerType: (*SnowflakeIdServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SnowflakeIdServer_Ping_Handler,
		},
		{
			MethodName: "GetID",
			Handler:    _SnowflakeIdServer_GetID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snowflake_id_server.proto",
}
